# Generated by Django 5.1.5 on 2025-02-04 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweeter_user', models.CharField(max_length=30)),
                ('tweet_caption', models.TextField(blank=True, null=True)),
                ('tweet_category', models.CharField(max_length=20)),
                ('tweet_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tweet_url', models.CharField(max_length=500)),
                ('hashtag_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
